containerization:
  - docker.io
  - docker-compose

kind_version: "0.11.1"
kubectl_version: "1.22.0"

kind_url: "https://kind.sigs.k8s.io/dl/v{{ kind_version }}/kind-linux-amd64"
minikube_url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
kubectl_url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"