- name: Install dependencies for anaconda
  apt:
    name: "{{ anaconda_dependencies }}"
    state: present
    force_apt_get: yes

- name: check for installation of Anaconda
  become: yes
  stat:
    path: '{{ anaconda_install_dir }}/bin/conda'
  changed_when: false
  register: anaconda_conda_binary

- when: not anaconda_conda_binary.stat.exists
  block:
    - name: download installer
      become: yes
      become_user: root
      get_url:
        url: '{{ anaconda_installer_url }}'
        dest: /tmp/{{ anaconda_installer_sh }}
        timeout: '{{ anaconda_download_timeout }}'
        mode: 0755

    - name: install
      become: yes
      become_user: root
      command: bash /tmp/{{ anaconda_installer_sh }} -b -p {{ anaconda_install_dir }}
      args:
        creates: '{{ anaconda_install_dir }}'

  always:
    - name: delete installer
      become: yes
      become_user: root
      file:
        path: /tmp/{{ anaconda_installer_sh }}
        state: absent