- block:
  - name: download kind
    get_url:
      url: "{{ kind_url }}"
      dest: "/usr/local/bin/kind"
      mode: 0755
    become: yes

  - name: download minikube
    get_url:
      url: "{{ minikube_url }}"
      dest: "/usr/local/bin/minikube"
      mode: 0755
    become: yes

  - name: download kubectl
    get_url:
      url: "{{ kubectl_url }}"
      dest: "/usr/local/bin/kubectl" #todo
      mode: 0755
    become: yes

  - name: install packaged containerization tools
    apt:
      name: "{{ containerization }}"
      update_cache: yes
      state: present
      force_apt_get: yes